var webseries=
[
/*change the episod number to '01' */
/*[name,bitly img id,totalEpisods,fristEpisodeLink],*/

['Pop Kaun S01','3Tq0jEu',6,'__wsdomain/WebSeries/Hotstar/Pop.Kaun.S01/Pop.Kaun.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv','https://dflinks.club/archives/21700'],
['Taj Divided by Blood S01','3KUHbMO',10,'__wsdomain/WebSeries/Zee5/Taj.Divided.by.Blood.S01/Taj.Divided.by.Blood.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv',''],
['Taaza Khabar S01','3GhKg5G',6,'__wsdomain/WebSeries/Hotstar/Taaza.Khabar.S01/Taaza.Khabar.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv','20292'],
['Kaleidoscope S01','3ia3qCB',8,'__wsdomain/WebSeries/NetFlix/Kaleidoscope.S01/Kaleidoscope.S01.E01.Hindi.English.720p.WEB-DL.ESub-DudeFilms.in.mkv','20272'],
['Pitchers S02','3vh3Iuk',5,'__wsdomain/WebSeries/Zee5/Pitchers.S02/Pitchers.S02.E01.Hindi.720p.WEB-DL.ESubs-DudeFilms.in.mkv','20099'],
['Kathmandu Connection S02','3HXtR8P',5,'__wsdomain/WebSeries/Sony.Liv/Kathmandu.Connection.S02/Kathmandu.Connection.S02.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv','20082'],
['Physics Wallah S01','3BFZuQg',6,'__wsdomain/WebSeries/Amazon.Prime/Physics.Wallah.S01/Physics.Wallah.S01.E01.Hindi.720p.WEB-DL.ESubs-DudeFilms.in.mkv','19856'],
['Blood Sex & Royalty S01','3U1Yixe',3,'__wsdomain/WebSeries/NetFlix/Blood.Sex.&.Royalty.S01/Blood.Sex.&.Royalty.S01.E01.Hindi.English.720p.WEB-DL.ESub-DudeFilms.in.mkv','19329'],
['Country Mafia S01','3EMx619',10,'__wsdomain/WebSeries/Zee5/Country.Mafia.S01/Country.Mafia.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv','19067'],
['Mukhbir The Story of a Spy S01','3g0nypy',8,'__wsdomain/WebSeries/Zee5/Mukhbir.The.Story.of.a.Spy.S01/Mukhbir.The.Story.of.a.Spy.S01.E01.Hindi.720p.WEB-DL.ESubs-DudeFilms.in.mkv','18775'],
['Breathe Into the Shadows S02','3hsjX3P',8,'__wsdomain/WebSeries/Amazon.Prime/Breathe.Into.the.Shadows.S02/Breathe.Into.the.Shadows.S02.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv','18630'],
['Tanaav S01','3A7OgU4',6,'__wsdomain/WebSeries/Sony.Liv/Tanaav.S01/Tanaav.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv','18716'],
['Flames 3','3TE54d3',5,'__wsdomain/WebSeries/Amazon.Prime/Flames/S03/Flames.S03.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Jhansi','3zp5hbY',6,'__wsdomain/WebSeries/Hotstar/Jhansi.S01/Jhansi.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Mismatched','3z5F8Ph',6,'__wsdomain/WebSeries/NetFlix/Mismatched/S01/Mismatched.S01.E01.Hindi.720p.WEB.DL.ESub-DudeFilms.in.mkv'],
['Good.Bad.Girl','3Mwc4Wy',9,'__wsdomain/WebSeries/Sony.Liv/Good.Bad.Girl.S01/Good.Bad.Girl.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['The.Family.Man.S02','3M0qrST',9,'__wsdomain/WebSeries/Amazon.Prime/The.Family.Man.S02/The.Family.Man.S02.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Hush.Hush.S01','3y1J2rX',7,'__wsdomain/WebSeries/Amazon.Prime/Hush.Hush.S01/Hush.Hush.S01.E01.Hindi.720p.WEBRip.ESubs-DudeFilms.in.mkv'],
['Jamtara.Sabka.Number.Ayega.S02','3UBbhHp',8,'__wsdomain/WebSeries/NetFlix/Jamtara.Sabka.Number.Ayega.S02/Jamtara.Sabka.Number.Ayega.S02.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['College.Romance.S03','3xwuKPA',5,'__wsdomain/WebSeries/Sony.Liv/College.Romance.S03/College.Romance.S03.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Criminal.Justice.Adhura.Sach.S01','3QJu1RX',5,'__wsdomain/WebSeries/Hotstar/Criminal.Justice.Adhura.Sach.S01/Criminal.Justice.Adhura.Sach.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Dahan.Raakan.Ka.Rahasya.S01','3qGs6TK',9,'__wsdomain/WebSeries/Hotstar/Dahan.Raakan.Ka.Rahasya.S01/Dahan.Raakan.Ka.Rahasya.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['House.of.the.Dragon.S01','3xuZG2K',4,'__wsdomain/WebSeries/HBO/House.of.the.Dragon.S01/House.of.the.Dragon.S01.E01.%7BHindi.(HQ)-English%7D.720p.HDRip-DudeFilms.in.mkv'],
['She Hulk Attorney at Law S01','3L8rMqf',5,'__wsdomain/WebSeries/Hotstar/She.Hulk.Attorney.at.Law.S01/720p/She.Hulk.Attorney.at.Law.S01.E01.Hindi.English.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Ms.Marvel.S01','3TWz6t6',6,'__wsdomain/WebSeries/hotstar/Ms.Marvel.S01/480p/Ms.Marvel.S01.E01.Hindi.English.480p.WEB-DL-DudeFilms.in.mkv'],
['Maharani.S02','Maharani.S02',10,'__wsdomain/WebSeries/Sony.Liv/Maharani.S02/Maharani.S02.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Udan.Patolas.S01','3SOTyvA',6,'__wsdomain/WebSeries/Amazon.Prime/Udan.Patolas.S01/Udan.Patolas.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Udan.Patolas.S02','3SOTyvA',6,'__wsdomain/WebSeries/Amazon.Prime/Udan.Patolas.S02/Udan.Patolas.S02.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['I.Am.Groot.S01','3AdsoHb',5,'__wsdomain/WebSeries/Hotstar/I.Am.Groot.S01/720p/I.Am.Groot.S01.E01.English.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Locke.And.Key','3QePItD',8,'__wsdomain/WebSeries/NetFlix/Locke.And.Key/S03/Locke.And.Key.S03.E01.Hindi.English.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Delhi.Crime.S01','3JLBPRq',7,'__wsdomain/WebSeries/Delhi.Crime.S01/Delhi.Crime.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Crash.Course.S01','3bJysOe',10,'__wsdomain/WebSeries/Amazon.Prime/Crash.Course.S01/Crash.Course.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['The.Sandman.S01','3p8ikJg',10,'__wsdomain/WebSeries/NetFlix/The.Sandman.S01/The.Sandman.S01.E01.Hindi-English.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['The.Great.Weddings.of.Munnes.S01','3dehMPy',10,'__wsdomain/WebSeries/Voot/The.Great.Weddings.of.Munnes.S01/The.Great.Weddings.of.Munnes.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['The Queens Gambit S01','3JBGvcr',7,'__wsdomain/WebSeries/NetFlix/The.Queens.Gambit.S01/The.Queens.Gambit.S01.E01.English.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Victim.S01','3JFij9i',4,'__wsdomain/WebSeries/Sony.Liv/Victim.S01/Victim.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Keep Breathing S01','3BwpEFY',6,'__wsdomain/WebSeries/NetFlix/Keep.Breathing.S01/Keep.Breathing.S01.E01.Hindi.English.720p.(10bit).WEB-DL.ESub-DudeFilms.in.mkv'],
['Dr Arora S01','3Os4xY4',8,'__wsdomain/WebSeries/Sony.Liv/Dr.Arora.S01/Dr.Arora.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Parampara S02','3czmIy3',5,'__wsdomain/WebSeries/Hotstar/Parampara.S02/Parampara.S02.E01.Dual.Audio.Hindi.Telugu.720p.WEB.DL.ESub-DudeFilms.in.mkv'],
['Indian Predator The Butcher of Delhi','3B9Fgze',3,'__wsdomain/WebSeries/Indian.Predator.The.Butcher.of.Delhi.S01/Indian.Predator.The.Butcher.of.Delhi.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Shoorveer','3z5XCiW',8,'__wsdomain/WebSeries/Hotstar/Shoorveer.S01/Shoorveer.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Jholachhap S01','3OccO2B',7,'__wsdomain/WebSeries/Voot/Jholachhap.S01/Jholachhap.S01.E01.Hindi.720p.WEB-DL-DudeFilms.in.mkv'],
['Saas Bahu Achaar Pvt Ltd S01','3nVkMCc',6,'__wsdomain/WebSeries/Zee5/Saas.Bahu.Achaar.Pvt.Ltd.S01/Saas.Bahu.Achaar.Pvt.Ltd.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Cyber Vaar S01','3OmsGQm',4,'__wsdomain/WebSeries/Voot/Cyber.Vaar.S01/Cyber.Vaar.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Bandon Mein Tha Dam S01','3OhovG5',4,'__wsdomain/WebSeries/Voot/Bandon.Mein.Tha.Dam.S01/Bandon.Mein.Tha.Dam.S01.E01.Hindi.720p.WEB-DL-DudeFilms.in.mkv'],
['The Broken news','https://bit.ly/3NDII8u',8,'__wsdomain/WebSeries/Zee5/The.Broken.News.S01/The.Broken.News.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Wan Kenobi S1','3NzA22u',2,'__wsdomain/WebSeries/Obi.Wan.Kenobi.S01/Obi.Wan.Kenobi.S01.E01.Hindi.English.720p.10bit.WEB-DL.ESub-DudeFilms.in.mkv'],
['Stranger Things S04','3NCsdZY',7,'__wsdomain/WebSeries/NetFlix/Stranger.Things.S04/Stranger.Things.S04.E01.Hindi.English.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Nirmal Pathaki Ghar Wapsi S01','3PKljDU',5,'__wsdomain/WebSeries/Sony.Liv/Nirmal.Pathak.Ki.Ghar.Wapsi.S01/Nirmal.Pathak.Ki.Ghar.Wapsi.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Escaype Live S01','3lvQ8y9',9,'__wsdomain/WebSeries/hotstar/Escaype.Live.S01/Escaype.Live.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Panchayat S02','3Mvxen4',8,'__wsdomain/WebSeries/Amazon.Prime/Panchayat.S02/Panchayat.S02.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Modern Love Mumbai S01','3LdGwCH',6,'__wsdomain/WebSeries/Amazon.Prime/Modern.Love.Mumbai.S01/Modern.Love.Mumbai.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Never Kiss Your Best Friend','3ONmqlI',8,'__wsdomain/WebSeries/Zee5/Never.Kiss.Your.Best.Friend.S02/Never.Kiss.Your.Best.Friend.S02.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Legends of the Ramayana','3rQfw5j',3,'__wsdomain/WebSeries/Discovery+/Legends.of.the.Ramayana.With.Amish.S01/Legends.of.the.Ramayana.With.Amish.S01.E01.720p.Web.dl.Esub-DudeFilms.in.mkv'],
['Guilty Minds Season 1','3k6RkaF',10,'__wsdomain/WebSeries/Amazon.Prime/Guilty.Minds.S01/720p/Guilty.Minds.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Anantham Season 1','3OvCN6s',8,'__wsdomain/WebSeries/Zee5/Anantham.S01/Anantham.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['London Files Season 1','3vF5wNg',6,'__wsdomain/WebSeries/Voot/London.Files.S01/London.Files.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Murder in Agonda Season 1','3OvXT4j',5,'__wsdomain/WebSeries/Amazon.Prime/Murder.in.Agonda.S01/Murder.in.Agonda.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Moon Knight Season 1','3KMyxNu',6,'__wsdomain/WebSeries/hotstar/Moon.Knight.S01/480p/Moon.Knight.S01.E01.Hindi.English.480p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Elite Season 5','3NZ63SJ',8,'__wsdomain/WebSeries/NetFlix/Elite.S05/Elite.S05.E01.Hindi.English.720p.10bit.WEB-DL.ESub-DudeFilms.in.mkv'],
['Gullak Season 3','3uqc0R2',5,'__wsdomain/WebSeries/Sony.Liv/Gullak.S03/Gullak.S03.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Abhay Season 3','3ungbN8',8,'__wsdomain/WebSeries/Zee5/Abhay.S03/Abhay.S03.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Eternally Confused and Eager for Love','3qu0VMo',8,'__wsdomain/WebSeries/NetFlix/Eternally.Confused.and.Eager.for.Love.S01/Eternally.Confused.and.Eager.for.Love.S01.E01.WebRip.720p.Hindi.5.1.x264.MSubs-DudeFilms.in.mkv'],
['Apharan Season 2','3u7fdn4',11,'__wsdomain/WebSeries/Voot/Apharan.S02/Apharan.S02.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Bloody Brothers','3CUsGCQ',6,'__wsdomain/WebSeries/Zee5/Bloody.Brothers.S01/Bloody.Brothers.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Sutaliyan','3sEuA6R',8,'__wsdomain/WebSeries/Zee5/Sutliyan.S01/Sutliyan.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['Rudra: The Edge Of Darkness','3pBQINq',6,'__wsdomain/WebSeries/hotstar/Rudra-The.Edge.of.Darkness.S01/Rudra-The.Edge.of.Darkness.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['The Fame Game','3C0cpLO',8,'__wsdomain/WebSeries/NetFlix/The.Fame.Game.S01/The.Fame.Game.S01.E01.720p.NF.WEB-DL.Esub-DudeFilms.in.mkv'],
['Bestseller','3pyz0uj',8,'__wsdomain/WebSeries/Amazon.Prime/Bestseller.S01/Bestseller.S01.E01.720p.AMZN.WEB-DL.Esub-DudeFilms.in.mkv'],
['Peacemaker','3p8NEYY',8,'__wsdomain/WebSeries/HBO/Peacemaker.S01/Peacemaker.S01.E01.English.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
['mithya','3scVhzq',6,'__wsdomain/WebSeries/Zee5/Mithya.S01/Mithya.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
["Dexter New Blood","3oXSiIY",10,"__wsdomain/WebSeries/Dexter.New.Blood.S01/Dexter.New.Blood.S01.E01.Hindi.English.720p.HEVC.10bit.WEB-DL.ESub-DudeFilms.in.mkv"],
["Raising Dion","3p0ddLv",9,"__wsdomain/WebSeries/NetFlix/Raising.Dion/S01/Raising.Dion.S01.E01.720p.Hindi.English.Esub-DudeFilms.in.mkv"],
["Inventing Anna","3I8QBAg",9,"__wsdomain/WebSeries/NetFlix/Inventing.Anna.S01/Inventing.Anna.S01.E01.Hindi.English.720p.HEVC.10bit.WEB-DL.ESub-DudeFilms.in.mkv"],
["Rocket Boys s1","3onJv2E",8,"__wsdomain/WebSeries/Sony.Liv/Rocket.Boys.S01/Rocket.Boys.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv"],
["The Great Indian Murder s1","3AVPAsq",9,"__wsdomain/WebSeries/hotstar/The.Great.Indian.Murder.S01/The.Great.Indian.Murder.S01.E01.720p.HS.WEB-DL.DD+5.1.H.265-DudeFilms.in.mkv"],
["Feria The Darkest Light","3siBvBb",8,"__wsdomain/WebSeries/NetFlix/Feria.The.Darkest.Light.S01/Feria.The.Darkest.Light.S01.E01.720p.10Bit.Hindi.English.Esubs-DudeFilms.in.mkv"],
["All of Us are DAEd","35oVTc8",12,"__wsdomain/WebSeries/NetFlix/All.Of.Us.Are.Dead.S01/All.Of.Us.Are.Dead.S01.E01.Hindi-English-Korean.720p.(10bit).WEB-DL.ESub-DudeFilms.in.mkv"],
["Unpaused Naya Safar","3FT1vbo",5,"__wsdomain/WebSeries/Amazon.Prime/Unpaused.Naya.Safar.S01/Unpaused.Naya.Safar.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv"],
["Bhaukaal Season 2","3IndHCB",10,"__wsdomain/WebSeries/MxPlayer/Bhaukaal.S02/Bhaukaal.S02.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv"],
["Human","3nn2PN6",10,"__wsdomain/WebSeries/hotstar/Human.S01/Human.S01.E01.Hindi.720p.WEB-DL.5.1.ESub.x264-DudeFilms.in.mkv"],
["Parampara Season 1","3mrvfF5",7,"__wsdomain/WebSeries/hotstar/Parampara.S01/Parampara.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv"],
["The WhistleBlower","3oWvbz0",9,"__wsdomain/WebSeries/Sony.Liv/The.WhistleBlower.S01/The.WhistleBlower.S01.E01.720p.Hindi.WEB-DL.ESub-DudeFilms.in.mkv"],
["The Witcher","3maR0Jd",8,"__wsdomain/WebSeries/NetFlix/The.Witcher/S01/The.Witcher.S01.E01.Dual.Audio.Hindi.English.720p.HEVC.WEB-DL.ESub-DudeFilms.in.mkv"],
["Qatil Haseenaon Ke Naam","3rWBWD0",6,"__wsdomain/WebSeries/Zee5/Qatil.Haseenaon.Ke.Naam.S01/Qatil.Haseenaon.Ke.Naam.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv"],
["Arya Season 2","31KRxKU",8,"__wsdomain/WebSeries/hotstar/Aarya/S02/720p/Aarya.S02.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv"],
["Money Heist Part 1","3y7cko1",5,"__wsdomain/WebSeries/NetFlix/Money.Heist.S05/480p/Money.Heist.S05.E01.Hindi.English.480p.WEB-DL.ESub-DudeFilms.in.mkv"],
["Hiccups and Hookups","3I485Ov",8,"__wsdomain/WebSeries/Hiccups.and.Hookups.S01/Hiccups.and.Hookups.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv"],
["Dil Bekaraar","3I70XAJ",10,"__wsdomain/WebSeries/hotstar/Dil.Bekaraar.S01/Dil.Bekaraar.S01.E01.720p.WEB-DL.x264-DudeFilms.in.mkv"],
["Illegal","3r5pMHr",8,"__wsdomain/WebSeries/Voot/Illegal.S02/Illegal.S02.E01.Hindi.720p.WEB-DL-DudeFilms.in.mkv"],
["Hawkeye","3DUs4wm",6,"__wsdomain/WebSeries/hotstar/Hawkeye.S01/480p/Hawkeye.S01.E01.480p.x264.Hindi.English.Multi.Esubs-DudeFilms.in.mkv"],
["The wheel of Time","32bz1ex",6,"__wsdomain/WebSeries/Amazon.Prime/The.Wheel.of.Time.S01/480p/The.Wheel.of.Time.S01.E01.Hindi.English.480p.WEB-DL.ESub-DudeFilms.in.mkv"],
["Your Honor Season 2","30DfgMQ",5,'__wsdomain/WebSeries/Sony.Liv/Your.Honor.S02/Your.Honor.S02.E01.720p.Web.Dl.Esub-DudeFilms.in.mkv'],
["Lost In Space","3ova992",10,'__wsdomain/WebSeries/NetFlix/Lost.in.Space/S02/480p/Lost.in.Space.S02.E01.480p.Hindi.Eng.WebDL.Esub-DudeFilms.in.mkv'],
["Akkad Bakkad Rafu Chakkar","3nZX07X",10,'__wsdomain/WebSeries/Amazon.Prime/Akkad.Bakkad.Rafu.Chakkar.S01/Akkad.Bakkad.Rafu.Chakkar.S01.E01.720p.x264-DudeFilms.in.mkv'],
["Call My Agent","3o75oTf",6,'__wsdomain/WebSeries/NetFlix/Call.My.Agent.Bollywood.S01/Call.My.Agent.Bollywood.S01.E01.Hindi.720p.WEB-DL.ESub-DudeFilms.in.mkv'],
["My Name","3BSziAc",8,'__wsdomain/WebSeries/NetFlix/My.Name.S01/My.Name.S01.E01.Hindi.Korean.720p.HEVC.WEB-DL.ESub-DudeFilms.in.mkv'],
["Tabbar SonyLiv","3FWSBdZ",8,'__wsdomain/WebSeries/Sony.Liv/Tabbar.S01/Tabbar.S01.E01.Hindi.720p.WEB-DL-DudeFilms.in.mkv'],
["Kota Factory season 2","3ALcKAB",5,'__wsdomain/WebSeries/NetFlix/Kota.Factory/S02/720p/Kota.Factory.S02.E01.Hindi.720p.WEB-DL.Esubs-DudeFilms.in.mkv'],
["House of Secrets","3v3bYNt",3,'__wsdomain/WebSeries/NetFlix/House.of.Secrets.The.Burari.Deaths.S01/480p/House.of.Secrets.The.Burari.Deaths.S01.E01.480p.WEB-DL.Hindi.ESub.x264-DudeFilms.in.mkv'],
];

var numSeries=webseries.length,
tempSr={},webseriesAry=[];
for(let i=0; i <webseries.length; i++){
	let valx=webseries[i],
	links=[];
	for(let j=1; j<=valx[2]; j++){
		links.push(valx[3].replace("__wsdomain/",seriesDomain).replace("E01","E"+get2dNum(j)));
	}
	tempSr[i]={
		name: valx[0],
		img: "https://bit.ly/"+valx[1],
		links
	};
	webseriesAry.push(tempSr[i]);
}
webseries=tempSr;
function get2dNum(n){
	return n>9?n:"0"+n;
}
